#!/bin/bash
echo "
Hello from Podman on SLE Micro!
This message shows that your installation appears to be working correctly.

To generate this message, Podman took the following steps:
 1. Podman pulled the "hello-world" image from the Docker Hub.
 2. Podman created a new container from that image which runs the
    executable that produces the output you are currently reading.
 3. Podman displayed it on your terminal.

To try something more ambitious, you can run an openSUSE container with:
 $ podman run -it registry.opensuse.org/opensuse/leap:latest bash

Lovingly copied from "hello-world" https://hub.docker.com/_/hello-world"


